#!/bin/bash

while true
do
/usr/local/mysql/bin/mysql --user="cooperacy" \
--password="c00p3r4t10n" \
--database="coo" \
--execute='SELECT @cousers:=COUNT(`active`) FROM `coo`.`users` WHERE `active` = '1'; \
SELECT @ideas:=COUNT(`stage`) FROM `coo`.`projects` WHERE `stage` = '7'; \
update `coo`.`projects` \
set collected = collected + 0.000000380517504 * @cousers / @ideas \
where stage = 7'
sleep 1
done

#12/365/24/60/60 = 0.000000380517504

#In case we want to change it into a node function:

##const mysql = require('mysql2')
#const connection = mysql.createConnection({ host: 'localhost', user: 'cooperacy', password: 'c00p3r4t10n', database: 'coo' })

#setInterval(function() {
#  console.log("Pooling on the river..")
#  var query1 = 'SELECT @cousers:=COUNT(`active`) FROM `coo`.`users`    WHERE `active` = "1";'
#  var query2 = 'SELECT @ideas:=COUNT(`stage`)    FROM `coo`.`projects` WHERE `stage`  = "7";'
#  var query3 = 'UPDATE `coo`.`projects` set collected = collected + 0.00002283105023 * @cousers / @ideas where stage = "7";'
#  connection.query(query1,
#    function(err, results, fields) {
#      console.log(results); // results contains rows returned by server
#      console.log(fields); // fields contains extra meta data about results, if available
#      console.log(err);
#    }
#  )
#  connection.query(query2,
#    function(err, results, fields) {
#      console.log(results); // results contains rows returned by server
#      console.log(fields); // fields contains extra meta data about results, if available
#      console.log(err);
#    }
#  )
#  connection.query(query3,
#    function(err, results, fields) {
#      console.log(results); // results contains rows returned by server
#      console.log(fields); // fields contains extra meta data about results, if available
#      console.log(err);
#    }
#  )
#}, 1000);
#'
