<template>
  <b-container class="m-0 p-0 pagecontainer">
    <br /><img
      class="page-header"
      src="~/assets/image/page/banners/main/integration.png"
    />

    <br />
    <p class="subheading diversity space center margin">
      LEARNING TO COOPERATE MEANS LEARNING TO INTEGRATE
    </p>
    <p class="base">
      Most conflictual situations are generated by different perspectives that
      polarize losing their
      <nuxt-link to="/main/cooperation#diversity" class="ad"
        >potential</nuxt-link
      >.<br />A little amount of contrast is useful and even good sign, but when
      it turns into conflict, you experience direct or indirect, verbal or
      physical violence. In that case you tend to polarize, that is, to defend
      your position as you would if you were under a death menace. We found
      interesting
      <nuxt-link to="/main/integration#solutions" class="ad"
        >solutions</nuxt-link
      >
      to conflictual interactions, but you can generally use
      <i>proportional creativity integration</i> as a rule of thumb.
    </p>

    <p class="subheading understanding space center margin">
      CREATIVITY EVOLVES CONTRAST
    </p>
    <p class="base">
      Proportional creativity integration needs training as we're used to
      address situations with another different approach, the win/lose one, in
      which the winning position is the only one respected. In proportional
      creativity you first establish a criteria -that could be voting or
      weighting opportunities- to measure situations, and then try to creatively
      integrate the diverse perspectives. There is not a standard recipe (..for
      a
      <a class="au" href="https://en.wikipedia.org/wiki/No_free_lunch_theorem"
        >free lunch</a
      >): you need to know the context well. Let's see two examples.
    </p>

    <p class="subheading understanding space center margin">
      INTEGRATION NARRATIVES
    </p>

    <!-- insert kitchen image here -->

    <p class="base">
      The first story is a simple one. In a company office, people want to use
      the kitchen zone for different purposes. Some want to use it as the
      standard lunch zone for the workers. Other people think cooking courses
      may be organized while some few other ones say they would use the
      colourful kitchen as an office. Three different views clashing one against
      another. Proportional space and time may solve the situation. The majority
      will use it as the lunch area, while the third group can use a
      proportional office space during working hours. Cooking workshops instead
      will be held in the weekend when nobody is working.
    </p>

    <p class="subheading understanding space center margin">CONTEXT</p>

    <!-- insert ancient library image here -->

    <p class="base mb-5">
      Another famous example tells of an ancient library, during summertime.
      It's very hot, a man opens a window, but a girl blocks him as that window
      is facing a restaurant: noise and various smells would fill the library
      and defocus the readers.<br /><br />
      The man insists and the two start to argue, conflict is near.. How would
      you solve this situation?<br /><br />
      Suddenly the librarian stopped the two, closed the window and.. opened
      another one on the other side of the library, allowing fresh air to enter
      with no noise nor cooking smells.<br />
      Once you know the context, creativity arises and
      <nuxt-link to="/main/integration#solutions" class="ad"
        >solutions</nuxt-link
      >
      are found in the integration of opposite, clashing but right perspectives.
    </p>

    <img
      class="page-header"
      src="~/assets/image/page/banners/main/solutions.png"
      name="solutions"
      id="solutions"
    />
    <p class="base">
      Contrast between ideas or people is part of the game, conflict is when
      contrast escalates into a form of violence. Equivalence, Trust, Care,
      Transparency, Freedom, Understanding and Diversity are your keys to foster
      solutions for transforming contrast in development and
      <nuxt-link to="/main/cooperation" class="ae">cooperation</nuxt-link>.
    </p>

    <p
      class="subheading diversity center space margin"
      name="diversity"
      id="diversity"
    >
      DIVERSITY: CREATIVITY, EXPERIMENTATION AND ROLES
    </p>
    <p class="base">
      Sometimes contrasts are based on two visions about a problem that are
      right and try to do the best. They collide because they want to do what is
      just. Give yourself some brainstorming time and be
      <nuxt-link to="/main/fun" class="ad">creative</nuxt-link>, you may find a
      new, strong, effective solution.<br />If the contrast is instead based on
      individuals with
      <nuxt-link to="/main/cooperation#diversity" class="ad"
        >different</nuxt-link
      >
      personalities, cultures and the like, every one of them should have the
      possibility to experiment solutions based on their personal preferences
      and knowledge or have a role that corresponds to their values, beliefs and
      vision. Everyone will feel part of the group that way. With possibility of
      experimentation and roles
      <nuxt-link to="/main/cooperation" class="ae">cooperation</nuxt-link> and
      <nuxt-link to="/main/cooperation#understanding" class="au"
        >understanding</nuxt-link
      >
      emerge and mutual enjoyment fulfills the group.
    </p>

    <p
      class="subheading understanding center space margin"
      name="understanding"
      id="understanding"
    >
      UNDERSTANDING: COMMON CODES
    </p>
    <p class="base">
      Does your group talk? Are the people ready to explain what they think?
      Does everyone listen? Finally, do the individuals comprehend each other?
      Talk, explain, listen, comprehend are four difficult steps in the way to
      understanding. In order to invoke those magic steps, the group may focus
      on the values and the beliefs in common. The values or the motivations
      could be profoundly similar even in a wide difference of personal views.
      Everyone of us is
      <nuxt-link to="/main/cooperation#diversity" class="ad"
        >different</nuxt-link
      >, and everyone of us sees things with a different perspective, trying to
      be happy in this very complex world. The key in creating the feeling of
      cooperation is
      <nuxt-link to="/main/cooperation#understanding" class="au"
        >understanding</nuxt-link
      >
      that everyone sees the world with complete different codes, so when you
      reciprocally share the way you see things it's possible to comprehend each
      other and find the right
      <nuxt-link to="/main/integration" class="ad">integration</nuxt-link>.
    </p>

    <p
      class="subheading freedom center space margin"
      name="freedom"
      id="freedom"
    >
      FREEDOM: THE RIGHT SPACE TO EVERYONE
    </p>
    <p class="base">
      Giving the right
      <nuxt-link to="/main/cooperation#freedom" class="af">space</nuxt-link> is
      a way to make people feel at ease without separating them. Nothing is
      worse than forcing to be together people who do not want to. If you are a
      few, try a pause or simply some space or distance between the people in
      conflict for a determined amount of time. If you are many, you can
      experience a live setup that foster cooperation organising an
      <nuxt-link to="/main/coopenspace" class="ac"
        >Open Space Cooperation</nuxt-link
      >.
    </p>

    <p class="base">
      <nuxt-link to="/login" class="ae">Join</nuxt-link> and
      <nuxt-link to="/main/participate" class="at">Participate</nuxt-link> in
      Cooperacy to see how these solutions can be of help in
      <nuxt-link to="/main/spread" class="ae">spreading</nuxt-link> the good
      energy of cooperation.
    </p>

    <p
      class="subheading transparency center space margin"
      name="transparency"
      id="transparency"
    >
      TRANSPARENCY: CONTEXTUAL POINT OF VIEW
    </p>
    <p class="base">
      The trick here is to expose everyone’s point of view in complete freedom.
      Be careful with this methodology and be ready to accept apparent
      unpleasant aspects. Bear very well in mind that what is requested is not
      to tell the truth right away, but to clearly expose
      <i>the contextual situation</i> from which your point of view
      <i>desumes</i> the truth you are going to expose. Saying "The wall is
      white" is different than saying "In my video camera, I see the blue wall
      as completely white."<br /><br />
      In search for a
      <nuxt-link to="/main/integration" class="ad"
        >proportional creative integration</nuxt-link
      >, tell in a
      <nuxt-link to="/main/cooperation#transparency" class="ai"
        >transparent</nuxt-link
      >
      way what is the minimum you need to be comfortable in the current
      situation and what are the limitations you face in your position. Also,
      express your desires in first person, trying to be specific as much as you
      can. For example, a sentence like "You don't listen to me" becomes "I feel
      like as I am not able to be understood. I would really like if I could
      talk for 5 minutes, no more, without interruption."
    </p>

    <p class="subheading care center space margin" name="care" id="care">
      CARE: BETTER CONTEXTS, BETTER FEELINGS
    </p>
    <p class="base">
      <nuxt-link to="/main/cooperation#care" class="ac">Care</nuxt-link> means
      respect and good coordination. The context, the environment and the
      services should be observed. Are you in a beautiful place? Are plants or
      animals respected around you? Are there colors? Is there good food and
      water? Are you feeling good? Are you tired and need a pause? Are you
      afraid of something? Are you happy instead? Can you find an area of your
      body in which that happiness is?<br />
      These questions seem to be a lot but they are very important. They can
      create a funny and bright mood and give you time to relax a bit and be
      more comprehensive with each other.
    </p>

    <p class="subheading trust center space margin" name="trust" id="trust">
      TRUST: TIME, MEASURES, EVALUATION
    </p>
    <p class="base">
      Give time its pace. Allow experience and adaptation to fix the situation
      and evaluate the results after a given amount of time. Sometimes fear may
      make people think in a negative way about events in the future. Faith in
      your solution and in those of others allows things to set up.
      <nuxt-link to="/main/cooperation#trust" class="at">Trust</nuxt-link> is
      important also in evaluations: when you test the solution and evaluate it
      with common and measurable criterias it will be easier to agree on a
      change or to decide together to trust your current approach.
    </p>

    <p
      class="subheading equivalence center space margin"
      name="equivalence"
      id="equivalence"
    >
      EQUIVALENCE: TURNS, COMBINATIONS, BALANCE
    </p>
    <p class="base">
      Is everyone allowed to play, relax or experiment? Do someone in the group
      work all the time while others don't? Is everyone respected in their
      views? Are there gaps and wide differences about the benefits they receive
      from the group? Turns may cycle good things and bad things and distribute
      them amongst the participants while sometimes different approaches may be
      combined into a single solutions, like joining innovation and safety, or
      business and caring. It is important to generate balance giving
      <nuxt-link to="/main/cooperation#equivalence" class="ae"
        >equivalent</nuxt-link
      >
      importance for all the members of the group, maintaining their individual
      differences. Enjoy the way others would do things: you will learn how they
      think. Understanding others will let them follow you if they make a
      mistake or if their solution is not so enjoyable.
    </p>
  </b-container>
</template>
<script>
export default {
  head() {
    return {
      title: 'Cooperacy - Proportional Creative Integration',
    }
  },
}
</script>
