<template>
  <div>
    <div class="page-container">
      <br /><img
        class="page-header"
        src="~/assets/image/page/banners/main/whitepaper.png"
      />
      <p class="base understanding">
        This white paper explains how the Cooperacy platform works in detail.
      </p>
      <p class="base">
        The platform is intended to be a social action network in which the
        coomembers develop their ideas. Cooperacy is the container of many
        internal cooperations, whose activities are coowned by Cooperacy and its
        coomembers.
      </p>
      <!-- COLLECTION FUND -->
      <p class="subheading understanding center space margin mt-5">
        THE COLLECTION FUND: COOPERATION IDEAS
      </p>
      <p class="base">
        The Cooperacy <i>collection fund</i> is an amount of money generated by
        every member's one euro monthly subscription. The money is allocated to
        the different ideas coming from the participants through their voting.
        Every 7 seconds, some "micro" euros are pre-allocated proportionally to
        the cooperation ideas: the more the votes a cooperation idea receives,
        the more the proportional amount of money allocated. The allocated funds
        are "frozen" until idea budget is fulfilled.
      </p>

      <p class="subheading understanding center space margin mt-5">
        COOPERATIONS STATES
      </p>
      <p class="base"></p>
      <div style="overflow-x: auto">
        <table style="width: 100%">
          <thead>
            <tr>
              <th class="baset">STATE</th>
              <th class="baset">DESCRIPTION</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td class="baset">Idea</td>
              <td class="baset">
                This state is the most common, and represent a cooperation idea
                or proposal.
              </td>
            </tr>
            <tr>
              <td class="baset">Pairing</td>
              <td class="baset">
                The cooperations may enter a 'pairing' state when the
                participants need to discuss how to resolve some
                misunderstandings. Once solved, the idea turns back to its
                previous state.
              </td>
            </tr>
            <tr>
              <td class="baset">Approval</td>
              <td class="baset">
                When a cooperation in the idea state has a budget and fulfills
                it, it enters the "approval" state, in which it has to pass all
                the budget steps.
              </td>
            </tr>
            <tr>
              <td class="baset">Testing</td>
              <td class="baset">
                If a cooperation has some strange or non transparent behavior,
                it could go into a testing state, in which all the cooperacy
                members may investigate its situation and test if everything is
                correct, legally consistent and fair.
              </td>
            </tr>
            <tr>
              <td class="baset">Caring</td>
              <td class="baset">
                Special state for cooperations that need some care or attention
                because in a delicate situation.
              </td>
            </tr>
            <tr>
              <td class="baset">Participation</td>
              <td class="baset">
                An "active" cooperation is one that is in fuction and may
                produce revenues which, after every working professional receive
                their salary, will go back to the main collection fund.
              </td>
            </tr>
            <tr>
              <td class="baset">Archived</td>
              <td class="baset">
                When a cooperation ends its function, it gets archived and can
                be given a feedback or used as a model for a new one.
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <p class="subheading understanding center space margin mt-5">
        COOPERATIONS CATEGORIES
      </p>
      <p class="base"></p>
      <div style="overflow-x: auto">
        <table style="width: 100%">
          <thead>
            <tr>
              <th class="baset">CATEGORY</th>
              <th class="baset">DESCRIPTION</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td class="baset">Funded</td>
              <td class="baset">
                This category indicates the cooperation idea participates to the
                possibility of receiving funds according to the common voting.
              </td>
            </tr>
            <tr>
              <td class="baset">Participated</td>
              <td class="baset">
                The "participated" cooperations have a budget determined by the
                collection of a fee. Events, courses and similar cooperations
                need a certain amount of participants to be activated. When the
                needed number is reached, they become active.
              </td>
            </tr>
            <tr>
              <td class="baset">Ecosystem</td>
              <td class="baset">
                The ecosystem category is related to cooperations that are like
                the funded ones but get promoted in the sense that they result
                as first in the search results.
              </td>
            </tr>
            <tr>
              <td class="baset">Voting</td>
              <td class="baset">
                The voting category is for voting only, so it does not receive
                funds but has governance effects. In order to issue a voting in
                your cooperation, just use your cooperation as parent and create
                a child cooperation with the votingh category. It doesn't give
                any results in the cooperation search.
              </td>
            </tr>
            <tr>
              <td class="baset">Evaluation</td>
              <td class="baset">
                The evaluation category is to allow people to evaluate some
                cooperation ideas. It does not give any results in the
                cooperation search, and it's not funded nor participated.
              </td>
            </tr>
            <tr>
              <td class="baset">Science, Education and Health</td>
              <td class="baset">
                The Science, Education and Health category is for not funded
                ideas or can be applied to funded cooperations - only after they
                become active. Its peculiarity is that it may be subject to
                testing by experts.
              </td>
            </tr>
            <tr>
              <td class="baset">Not Funded</td>
              <td class="baset">
                A simple cooperation idea based on voluntary funding or just to
                gather action and interest.
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <p class="subheading understanding center space margin mt-5">
        AFTF MULTIDIMENSIONAL VOTING
      </p>
      <p class="base">
        In Cooperacy we don't vote for people, but for ideas. Both ideas and
        voting are anonymous until the ideas become cooperations. After that,
        all the information will be transparent for checking purposes. This is
        called AFTF, Anonymous First, Transparent Forever-after: the beginning
        anonymity allows to boost collective intelligence and transparency
        enhances cooperation afterwards. <br />
        Anybody can vote for as many ideas they want. In order to leverage more
        collective intelligence, there are different kinds of votes:
      </p>
      <br />
      <!-- VOTING -->
      <p class="base equivalence">Equivalence</p>
      <p class="base">
        It determines the proportional allocation of funds from the money pool.
        Technical: the proportions are calculated with the number of the
        equivalence votes the idea has (Ei), divided by the total (Et) of all
        the equivalence votes all the ideas have (Ei / Et ). If funds for a
        budget cooperation idea get to more than 50%, the cooperation gets to a
        boost bonus and its funding allocation will be as quick as if it had 80%
        of the votes. Equivalence votes in a participated cooperation indicate
        pre-buy as a client, that is, subscription to a course or pre-purchase
        to a concert. This vinculates the trustee to the payment of the relative
        pre-purchase or fee when the cooperation becomes active. The participant
        can change the vote anytime but not after the cooperation becomes active
        after the reaching of the needed budget.
      </p>
      <br />

      <p class="base trust">Trust</p>
      <p class="base">
        Trust votes make the cooperation skip the human resources budget step.
        Technical: if the cooperation trust votes (Ti) are more than half of the
        cooperation equivalence votes (Ti > 50% Ei) the human resources budget
        step is automatically approved.
      </p>
      <br />

      <p class="base care">Care</p>
      <p class="base">
        When care-voted, the cooperation gains more visibility. Technical: Ideas
        visibility is enhanced by ordering them by Care. This emotional response
        in the future could also be generated thanks to biofeedback sensors.
      </p>
      <br />
      <p class="base transparency">Transparency</p>
      <p class="base">
        This is a downvote to declare hidden information, corruption, cheating
        or spamming. Technical: Transparency-voting triggers a message in which
        you communicate what others do not see. If a Transparency vote is
        "unvoted", the cooperation may go into a "pairing" state where the
        participants discuss. After 90 days of pairing, if nothing happens the
        idea may be split or removed and in case the budget is turned back to
        the money pool. During this period the participants can better explain
        to unvoters the cooperation idea development in order to restore
        transparency. If the idea is unblocked, the count of 90 days is
        canceled. Transparency voters are never anonymous. Highest
        transparency-unvoted cooperations may win the joke/trolling prize of the
        year.
      </p>
      <br />
      <p class="base freedom">Freedom</p>
      <p class="base">
        Freedom-voting means you would like to work for the idea or participate
        into the decision making. Every cooperation can instead be discussed and
        observed in full transparency anyways. Technical: if a hudget is
        requested, freedom-votes count for the requested hudget. Moreover,
        freedom-voters will be chosen automatically unless their number is
        higher than the requested hudget, in which case a selection will occur.
        If a hudget is not requested, the idea participants will first review
        the freedom-voters list for the budget "hudget" step. Freedom-voters
        automatically become participants when the cooperation becomes active.
      </p>
      <br />

      <p class="base understanding">Understanding</p>
      <p class="base">
        This vote refers to the idea comprehension or nerditude and
        automatically approves the Setup phase. Technical: if the cooperation
        understanding votes are more than the 70% of the top understanding voted
        cooperation (Ui > U(max)*70%) the Setup budget release step is
        automatically approved.
      </p>
      <br />
      <p class="base diversity">Diversity</p>
      <p class="base">
        When a funded cooperation has a strong “bizardry” (diversity-votes), it
        has more opportunities to be randomly approved. Technical: ideas has a
        diversity percentage ( Di / Dt ). Every idea, the first day of a season
        (equinoxes and solstices), is given a random percentage value between 0%
        and 10%, to which the diversity percentage is added and then randomly
        multiplied by -1. The idea that has the highest “Bizardry” has a virtual
        added equivalence-votes percentage of +50% [( Ei + 50% Et ) / Et ].
        Warning: 10 diversity votes lower the equivalence ones by 1.
      </p>
      <br /><br />
      <p class="subheading understanding center space margin mt-5">
        BUDGET RELEASE STEPS
      </p>
      <p class="base">
        The budget release process is divided into 7 steps which have a three
        days approval voting time in which the process could be halted and the
        people in charge can be changed for corruption or security reasons. Only
        people who equivalence-voted, participated or are relative to the module
        will be notified of the phases. Participants are therefore allowed to
        vote even if they are external to the module but only if they really
        care, as they won’t be notified otherwise. Every step is also voted for
        its transparency and sustainability.
      </p>
      <br />
      <div style="overflow-x: auto">
        <table style="width: 100%">
          <thead>
            <tr>
              <th class="baset understanding">STEPS</th>
              <th class="baset understanding">% Released</th>
              <th class="baset understanding">% Incremental</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td class="baset">Business Plan</td>
              <td class="baset">3%</td>
              <td class="baset">3%</td>
            </tr>
            <tr>
              <td class="baset">Human Resources</td>
              <td class="baset">10%</td>
              <td class="baset">13%</td>
            </tr>
            <tr>
              <td class="baset">Setup</td>
              <td class="baset">12%</td>
              <td class="baset">25%</td>
            </tr>
            <tr>
              <td class="baset">Production</td>
              <td class="baset">50%</td>
              <td class="baset">75%</td>
            </tr>
            <tr>
              <td class="baset">Kick Off</td>
              <td class="baset">12%</td>
              <td class="baset">87%</td>
            </tr>
            <tr>
              <td class="baset">Fine Tuning</td>
              <td class="baset">10%</td>
              <td class="baset">97%</td>
            </tr>
            <tr>
              <td class="baset">Celebrate</td>
              <td class="baset">3%</td>
              <td class="baset">100%</td>
            </tr>
          </tbody>
        </table>
      </div>
      <br /><br />
      <p class="subheading understanding center space margin mt-5">
        OTHER NOTES
      </p>
      <p class="base">
        Any direct donation to an idea counts as dedicated donated budget.
        Donated budget and pre-allocated budget count for the idea budget to be
        turned into an approval cooperation, but donated budget cannot be
        returned to the collection fund unless the idea is rescinded or
        abandoned.<br />
        Once the idea has reached the budget and/or hudget, the participants of
        the idea are kept frozen during the approval cooperation phase until it
        is turned into an active cooperation. The budget release milestones
        deadlines are chosen according to the Cooperacy
        <nuxt-link to="/main/governance" class="af">governance</nuxt-link>
        scheme.<br />
        Eventual contrasts not resolved in the 7 budget milestones are solved
        with a transparent voting kept live for three days, in which the
        participants can change their votes. The coordinators can creatively
        integrate the contrasting positions according to the seven solutions. At
        the end of a deadline time, the milestone should be decided.<br />
        All the contrasting votes not integrated reduce the budget, which goes
        back to the collection fund. In that case, the cooperation turns back to
        the idea state, keeping the milestones approved, and waits again for the
        fulfilment of the missing budget cut due to contrasting positions.<br />
        When an idea becomes an approval cooperation, the idea is “born”, and
        has a birthdate. When the approval becomes an active cooperation it can
        receive a three level feedback by the coomembers using the same
        votes.<br />
        In case of “death” of an active cooperation, for example when a course
        ends, or a backery is sold, its final step is to be archived. This turns
        the active cooperation into an archived one and the AI analyzes it while
        the participants may still give some feedback.<br />
        Participants Gender (M / F / Other) will be aggregated in order to
        inidicate in the future the cooperation gender composition.<br />
        Cooperations may have internal cooperation ideas, for example a language
        institute that wants to add a new language course. Budget ideas that
        want to be funded by the Cooperacy collection fund must be children of
        the Cooperacy base cooperation to receive any budget pre-allocation.
        Only afterwards they can be inserted as subcooperations of any main
        cooperation.<br />
      </p>

      <!-- <p class="subheading understanding center space margin mt-5">CO-DONATIONS</p>
      <p class="base">
        Co-donation is an alternative way in which you can help an idea to find
        its budget. When you hit on co-donate, you choose a maximum amount you
        are willing to donate for filling up the idea budget, if all the other
        co-donators are willing to donate the same. The system periodically
        evaluates the lowest of all amounts promised and multiplies for the
        number of the co-donators in order to see if the total budget is
        reached. If not, the system evaluates other combination possibilities
        able to reach the budget, like excluding lower donation amounts. Once a
        possible co-donation is found, the idea is turned into a cooperation and the
        codonations are billed to your bank account, credit card or any other
        possibility the website allows.
      </p> -->

      <p class="subheading understanding center space margin mt-5">
        THE COOPERACY COOPERATIONS AS MODULES
      </p>
      <p class="base">
        As you see, there is a modular design in the cooperations. The
        modularity helps to create open source blueprints for the whole platform
        community.<br />
      </p>

      <p class="base">
        It is advised that the active participants should be maximum 150 and
        have maximum two coordinators. The module is continuously subject to the
        feedback of the participants and the voters. Even after years any
        participant can decide if something was good or bad, influencing the
        memory and the future AI of the system.<br />
      </p>
    </div>
  </div>
</template>
<script>
export default {
  head() {
    return {
      title: 'Cooperacy - The White Paper'
    }
  }
}
</script>
