<template>
  <div>
    <div class="page-container">
      <br /><img
        class="page-header"
        src="~/assets/image/page/banners/aboutus.png"
      />
      <p class="base">
        Cooperacy is a nonprofit project aiming to support our social ecosystem
        fostering the enjoyment of cooperation: on a more technical side, this
        is achieved transforming the current
        <a href="https://en.wikipedia.org/wiki/Pareto_distribution" class="au"
          >power law</a
        >
        distribution of resources, decisions and activities into a more even
        one.<br /><br />
        The
        <nuxt-link to="/platform" class="ai">Cooperacy Platform</nuxt-link> is
        the base of Cooperacy circular economic ecosystem. The participants
        voluntarily pool one euro per month into a common sum in order to fund
        their own ideas. The profits generated by these ideas goes back to the
        common pool. This triggers a co-owned virtuous process. To fund itself,
        Cooperacy offers also parallel services and activities:
        <nuxt-link to="/overview" class="ai">Cooperacy Overview</nuxt-link>
        is a measurement of the cooperation amount in larger organizations or
        institutions in order to promote their resilient growth. For example,
        the
        <nuxt-link to="/cci" class="ai">Cooperation Context Index</nuxt-link>
        shows the possibility of cooperation in most of the countries in the
        world.<br />
        <br />
        <nuxt-link to="/openecosystem" class="ai"
          >Cooperacy Experience</nuxt-link
        >
        is the live application of the Cooperacy model. The participants of any
        organization or community can enjoy a natural social system able to
        generate collaboration, innovation and problem solving.<br /><br />
        <nuxt-link to="/research" class="ai">Cooperacy Research</nuxt-link> is
        instead a continuous scientific investigation about possible social
        systems based on cooperation and ecosystemic awareness.<br /><br />
        If you consider our society and its natural ecosystem as a whole living
        organism, being part of Cooperacy means supporting this organism with
        the enjoyment of cooperation.
        <nuxt-link to="/login" class="ae">Joining</nuxt-link> the voluntary pool
        will let you experiment and support a different social ecosystem based
        on cooperation and common enjoyment.<br /><br />
      </p>
    </div>
    <div>
      <p class="subheading transparency center space">THE TEAM</p>
      <div class="row">
        <div
          class="col-lg-3 col-md-3 col-sm-3 col-xs-12 text-center"
          style="display: flex; flex-wrap: wrap; justify-content: center;"
        >
          <img
            class="about"
            src="~/assets/image/page/aboutus/amdp.png"
            alt="null"
          /><br />
          <p>
            Alessandro Merletti De Palo<br />
            <i>Co-founder and coordinator of Cooperacy</i>
          </p>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 text-center">
          <img
            class="about"
            src="~/assets/image/page/aboutus/mario.png"
            alt="Mario Sabatino"
          /><br />
          <p>
            Mario Sabatino Riontino<br />
            <i>Coorporate Project</i>
          </p>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 text-center">
          <img
            class="about"
            src="~/assets/image/page/aboutus/framba.png"
            alt="null"
          /><br />
          <p>
            Federica Framba<br />
            <i>Designer</i>
          </p>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 text-center">
          <img
            class="about"
            src="~/assets/image/page/aboutus/ali.png"
            alt="null"
          /><br />
          <p>
            Ali Akhtari<br />
            <i>Front-End Developer</i>
          </p>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 text-center">
          <img
            class="about"
            src="~/assets/image/page/aboutus/alessia.png"
            alt="null"
          /><br />
          <p>
            Alessia De Santis<br />
            <i>Public Administration Projects</i>
          </p>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 text-center">
          <img
            class="about"
            src="~/assets/image/page/aboutus/marco.png"
            alt="null"
          /><br />
          <p>
            Marco Marincola<br />
            <i>Engineer</i>
          </p>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 text-center">
          <img
            class="about"
            src="~/assets/image/page/aboutus/ilario.png"
            alt="null"
          /><br />
          <p>
            Ilario Tito<br />
            <i>Co-founder</i>
          </p>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 text-center">
          <img
            class="about"
            src="~/assets/image/page/aboutus/enea.png"
            alt="null"
          /><br />
          <p>
            Enea Barbetta<br />
            <i>Developer</i>
          </p>
        </div>
      </div>
    </div>
    <div class="mt-2 pt-3">
      <br />
      <p class="subheading transparency center space">FINANCE</p>
      <br />
      <p class="base">
        We like so much transparency that we want everyone to be able to know
        our bank account balance and inspect our paypal account. We have nothing
        to hide.<br />
        <span class="transparency up">Bank account:</span>
        our bank information is: IBAN IT61D0623001623000043225634 BIC/SWIFT
        CRPPIT2P277 - Filiale AG 23 00277 - Cariparma, via della Moscova 53
        Milano 20121 and the current bank balance is around 800 euros, updated:
        16 November 2019<br />
        <span class="transparency up">Paypal:</span>
        you can access our account from the standard paypal login with
        COOPERATION + password cooperation2016
      </p>
      <br />
      <p class="subheading transparency center space">LEGAL STUFF</p>
      <br />
      <p class="base">
        The Cooperacy Association was founded in Italy, Milan, the day
        21/07/2015. Its current address is Via della Moscova 39, 20121 Milano.
      </p>
      <br />
      <p
        id="contributors"
        name="contributors"
        style="color: #22DDEE; font-size: 24px; font-weight: bold; margin-bottom: 10px;"
      ></p>
      <p class="base">
        We're still doing some more work to allow better transparency. If you
        don't see something you're curious of, please
        <nuxt-link to="/contact" class="ai">ask</nuxt-link> for more information
        to be shown in this page.<br />
        Moreover, if you want, have a look at what could be
        <nuxt-link to="/aboutyou" class="ac">your</nuxt-link> interest in
        Cooperacy.
      </p>
    </div>

    <!-- CAROUSEL -->
    <b-row class="mt-5">
      <b-col cols="12">
        <div>
          <b-carousel
            id="testimonials"
            controls
            indicators
            img-width="600"
            img-height="200"
          >
            <b-carousel-slide
              img-blank
              img-blank-color="#0dd"
              text="In Cooperacy I’ve seen the freedom of the individual in relation
                to the freedom of others, a continuous oscillation of
                equilibria, with unassuming attitude, following an easy flow and
                the spontaneous actions of people."
              caption="Carola"
            >
            </b-carousel-slide>

            <b-carousel-slide
              img-blank
              img-blank-color="#0dd"
              text="I see Cooperacy - beyond its social goal – as a path made of
                people who want to improve themselves and the world around them,
                building something beautiful and useful for all. In a world
                based on the mindless continuous consumption of goods, living on
                a different constructive mentality can be an amazing gift for
                ourselves and the people we love."
              caption="Lorenzo"
            >
            </b-carousel-slide>

            <b-carousel-slide
              img-blank
              img-blank-color="#0dd"
              text="There will be a day in which human beings will look to each
                other with the same love they have for their children. A day in
                which we will all be mutually parents and children at the same
                time. You don’t ask yourself if investing energy for a child
                will bring you an economic advantage. Now it’s not like that
                yet, but there are many movements indicating that global
                awareness is changing. Directions are visible and the so called
                “critical mass” is gradually becoming consistent. Cooperacy is
                one of this good movements having strong correlations with the
                concreteness of doing. I really feel like an ancient knight when
                I pay my humble duty - a small thing to do, but a big impulse to
                the nobility of my spirit."
              caption="Albino"
            >
            </b-carousel-slide>

            <b-carousel-slide
              img-blank
              img-blank-color="#0dd"
              text="I felt Cooperacy in my belly, since the first read. Then to make
                it go up and reach my mind, I fight with it. Yes, it’s like
                getting into fights. It drains me out and at the same time it
                lends a hand to make me get up again. It challenges me every
                day, it turns upside down my perspectives, it opens myself to
                new possibilities. It teaches me, while other times it allows me
                to teach or better share what I think I have learned. It’s my
                inner mountain."
              caption="Beatrice"
            >
            </b-carousel-slide>

            <b-carousel-slide
              img-blank
              img-blank-color="#0dd"
              text="Cooperacy, for me, it’s overall doing things together
                cheerfully. I hope you can have fun in Cooperacy like I do,
                participating to its construction with your ideas and your
                enthusiasm."
              caption="Ilario"
            >
            </b-carousel-slide>

            <b-carousel-slide
              img-blank
              img-blank-color="#0dd"
              text="Most of my friends remember me with my age. 15. I'm Kurd and
                raised in Qorveh, where Turks, Kurds, Persians coexist together
                (#diversity ;-) ). My mother is a Turk and my father is a Kurd.
                I'm a #gamification consultant. In Cooperacy I found that game
                design (and gamification) has a bad paradigm nowadays:
                cooperation is better (competition sucks ;-) ). As a game
                designer, accepting this fact was very hard for me. In game
                design and gamification, we have a lot of theories, techniques,
                and systems quoted on competition, a powerful drive in the human
                mind. Now with Cooperacy, We are trying to design games and ARGs
                to teach cooperation to high school students. And as an Iranian,
                I really love to test this gamified system to help my people.
                And make the world a better place. It is what Alessandro taught
                me: “it's not me, nor you, but the things we can do together.”"
              caption="Ali"
            >
            </b-carousel-slide>

            <b-carousel-slide
              img-blank
              img-blank-color="#0dd"
              text="It was a feeling of serendipity, calm awareness going through my
                smile. It was a particular period of my life: I had realized not
                only the present condition of the world we are living in, but
                also the great opportunity We have to address its problems. I
                simply thought:“I need to act, now”. I recognized in Cooperacy a
                peaceful awareness but also a decisive willingness to make it
                happen. Thanks to Cooperacy I did get to know several people,
                lovable people and I have been “since then” an enthusiast
                messenger of Cooperacy's values. I am truly fascinated by
                Cooperacy especially because its ideas are simpler to experience
                than to explain. There’s research in it, social research. And I
                strongly believe that this kind of approach is crucial in our
                time. I trust Cooperacy, nowadays this is an incredibly
                effective starting point. While writing this my hands literally
                cried over my laptop lol"
              caption="Davide"
            >
            </b-carousel-slide>

            <b-carousel-slide
              img-blank
              img-blank-color="#0dd"
              text="To me, it seemed a different idea than the others I heard about,
                during a period in which words like “start-up”, “business angel”
                and “innovation” were imposing themselves on the media agenda.
                Moved by the curiosity raised during the conversations with the
                group - that was forming and growing in the meantime - I read
                the book The Chalice and the Blade by R. Eisler. I found it so
                interesting that I thought it was worthy taking part in a more
                active way."
              caption="Giosetta"
            >
            </b-carousel-slide>

            <b-carousel-slide
              img-blank
              img-blank-color="#0dd"
              text="My first impression was I didn’t understand what was this group
                who was suggesting ways to make other people better communicate
                between themselves, nevertheless my internal curiosity spirit
                led me to meet Alessandro, Sara, Bea, Ilario and other
                coordinators of Cooperacy. At the end my inner spirit admitted
                Cooperacy has no definitions, you can only perceive it while you
                live it surrounded by the enthusiasm and the force of its
                participants."
              caption="Walter"
            >
            </b-carousel-slide>

            <b-carousel-slide
              img-blank
              img-blank-color="#0dd"
              text="Cooperacy is something I’ve been thinking about for some time,
                since when I understood that competition creates unhappiness."
              caption="Justin"
            >
            </b-carousel-slide>

            <b-carousel-slide
              img-blank
              img-blank-color="#0dd"
              text="A year ago Facebook showed me the Cooperacy link and I literally
                dove in it because I felt it was like the water in which I
                always wanted to swim into. In these months I often had the fear
                to drown and I went back to the shore. Nevertheless, the will to
                be in the waters has been stronger and thanks to some patient
                guidance by Alessandro, the sustain of Ilario and Beatrice I am
                learning to stay in the waters even when it frightens me, to
                trust the group and to flow together with all the rest. I feel
                like I am becoming water too and it’s amazing!"
              caption="Sara"
            >
            </b-carousel-slide>

            <b-carousel-slide
              img-blank
              img-blank-color="#0dd"
              text="What brought you to join Cooperacy? The fact that Cooperacy is
                trying to dissolve the most toxic superstition: the myth
                according to which the world is nothing more that a bloody
                battlefield in which “kill or be killed” it’s the only valid
                strategy."
              caption="Nicola"
            >
            </b-carousel-slide>

            <b-carousel-slide
              img-blank
              img-blank-color="#0dd"
              text="Born and raised in a small town in Trentino, surrounded by
                mountains and nature: a place where the sense of community, the
                value of cooperation and the care for the environment are
                strongly felt. Cooperacy!"
              caption="Federica"
            >
            </b-carousel-slide>

            <b-carousel-slide
              img-blank
              img-blank-color="#0dd"
              text="I needed a little bit of color in the gray days of mine. And in
                Cooperacy there is a rainbow of personalities one different than
                another, all full of enthusiasm and energy, with which to share
                ideas and work together. In Cooperacy I found a lot of people
                who work together well, and that overall they have fun doing it."
              caption="Enea"
            >
            </b-carousel-slide>

            <b-carousel-slide
              img-blank
              img-blank-color="#0dd"
              text="Although I have always been a supporter of a model based on
                hierarchies, I have always wondered if the world I dreamed was
                the right one. Discussing with Alessandro and listening to the
                Cooperacy concept, I was intrigued by the thought that something
                could (and perhaps should) change compared to certain ideas,
                appreciating the innovative way in which the cooperation science
                interpreted models."
              caption="Sabatino"
            >
            </b-carousel-slide>

            <b-carousel-slide
              img-blank
              img-blank-color="#0dd"
              text="A mechanism that sets the human being in the centre of
                everything. I said to myself: here there’s a new and original
                material, so I jumped on this train which costs just a coffee
                per month!"
              caption="Franz"
            >
            </b-carousel-slide>

            <b-carousel-slide
              img-blank
              img-blank-color="#0dd"
              text="I new since time that worst damage in most of human social
                environments come from the fact that every relationship starts
                with the presumption of knowing how to relate, communicate and
                cooperate. This presumption is false in almost all cases. We
                need courage, creativity and competence to change this
                condition, and Cooperacy has all the needed skills to accomplish
                it."
              caption="Igor"
            >
            </b-carousel-slide>

            <b-carousel-slide
              img-blank
              img-blank-color="#0dd"
              text="In Cooperacy I look for a model that would bring cooperation
                without leveraging over “noble sentiments”."
              caption="Marco"
            >
            </b-carousel-slide>

            <b-carousel-slide
              img-blank
              img-blank-color="#0dd"
              text="Cooperacy has been able to bring the creation of a smooth flow
                of communication in a social environment that wasn’t incline to
                establish good relations between the people. That is why I came
                to see what happens here. Without knowing if I will be able to
                be useful, but with that feeling that I want to understand
                something that intrigues me and to understand how to utilise it,
                I decided to join."
              caption="Francesco"
            >
            </b-carousel-slide>

            <b-carousel-slide
              img-blank
              img-blank-color="#0dd"
              text="Cooperacy has been growing these months a lot and it is
                impressive to see the continuous exchange of ideas, the
                cheerfulness and the seriousness with which the participants
                cooperate together in the projects."
              caption="Sarah"
            >
            </b-carousel-slide>

            <b-carousel-slide
              img-blank
              img-blank-color="#0dd"
              text="In these months I've seen people of different perspecitves to
                come and participate. While in Cooperacy, many of them decided
                to make big changes in their private lives. Cooperacy has been a
                common 'origin' able to make them to desire and recognize
                themselves in the actions they do everyday. They experienced the
                feeling of cooperation and naturally desired their social
                ecosystem to be based on redistribution of wealth, activities
                and power with proportional creative integration. In other
                words, the world as a pleasant and enjoyable place for everyone."
              caption="Alessandro"
            >
            </b-carousel-slide>
          </b-carousel>
        </div>
      </b-col>
    </b-row>
  </div>
</template>
<script>
export default {
  head() {
    return {
      title: 'Cooperacy - About Us'
    }
  }
}
</script>
<!--
/*

(44,	'Welcome. This is a fast page to get you quickly into action.\n\n== 1. Write to cooperacy@cooperacy.org and tell us YOUR GMAIL and that you want to be part of cooperacy.\n\n2. You will be redirected to the main folder of cooperacy. You can only view files at first, feel free to browse and understand.\n\n3. Have a look at the \"planning cooperacy\" excel file. Pickup a task and ask the relative coer what you can do or just ask permission on the file, put your name on a task and do it.\n\n== Terminology ==\n\n{| class=\"wikitable\"\n|Cooperation = acting together with mutual enjoyment (see [http://sites.lsa.umich.edu/collectiveintelligence/wp-content/uploads/sites/176/2015/05/Merletti-2015-CI-Abstract.pdf article])\n|Coo(s) = cooperation project(s)\n|Coer(s) = cooperative person(s)\n|}\n\n== Background ==\n\nWe want to share the \'\'cooperative-diversity\'\' culture. A culture in which economy does not make private margins, but all margins are kept in a fund that is used for the participants. A culture of inclusion. If someone is different, a different role and space will be given to that person. We want to diffuse it starting with the findings from a multidisciplinary scientific-academic approach relative to the diversity and cooperation theories.\nSee first base [http://sites.lsa.umich.edu/collectiveintelligence/wp-content/uploads/sites/176/2015/05/Merletti-2015-CI-Abstract.pdf approach] by amdp and other coers at the collective intelligence conference 2015 in silicon valley.\n\nWe don\'t want to change the current system, we want to have the space for a different one. A cooperative economy and a competitive one can coexist.\n\nCooperacy is not charity, nor a business oriented company, nor a communist party: we don\'t homologate. We have NO STANDARDIZED MORALS, we want to EXPERIMENT and GIVE SPACE to every diversity. Just keep respecting others who do not want to think like you or follow you.\nIn general:  NO PHYSICAL VIOLENT PREVARICATION,  NO FORCING OR MANIPULATING ACTIONS, KEEP DIVERSITY SPACE.\n\nCooperative-diversity principles:\n\n1 - If you \'\'disagree\'\', ASK FOR YOUR DIVERSITY SPACE, intellectually or literally: get more space or distance around you or for yourself. (Diversity, Transparency, Freedom, Care)\n\n2 - If you have with some others a COMMON RESOURCE, be EQUIVALENT in using it together. (Equivalence and Trust, Common Codes)\n\n== Principles ==\n\nEquivalence (we\'re not equal, we want equivalent lives and good stories to tell)\n\nTrust (or reliability --and preferably commitment)\n\nCare (Physical, psychological, attentive care. Respect.)\n\nTransparency (Honesty and ability TO RECEIVE TRUTH WITHOUT JUDGING)\n\nFreedom of choice (No golden cage slaveries nor forced impositions)\n\nCommon Codes (we need to have common codes along our personal ones to understand each other, bridges, communicaiton, understanding)\n\nDiversity (Identity and space for every diversity, avoiding homologation with sperimental areas and freedom to play games and dream)\n\n\nWe play the game of cooperation and we have a pet. This pet is called Distortion. When the pet is little, we make funny mistakes and kids laugh. When the pet gets too BIG, it will lead us to war between us and against diversities. \nDistortion gets bigger with distortions: prejudices, forced homologation, misunderstanding.\n\n== Group steps 2016 ==\n\nWe want to create a worldwide CoBank to realize our coos.\n\nEvery participants gives the equivalent of the Italian purchasing power of an Euro in July 2015. (Haiti coers would give less, Dubai coers would give more)\n\nWe try to invest them in a participated environment. We choose together and everything will be owned by the CoBank\'s fund, so anybody participating will have a share and access to it.\n\nNow we need a new website.\n\nThen we\'ll need a Foundation and a Bank, in order to fund our activities and jobs with no transaction costs.\n\nIt\'s a wonder. It\'s up to us.',	'utf-8'); -->
