<template>
  <div>
  <br /><img class="page-header" src="~/assets/image/page/banners/solutions.png" />
  <p class="subheading diversity center space margin">THE EVOLUTION OF CONTRAST</p>
  <p class="base"> Contrast between ideas or people may be evolved in different ways using <a class="ad" href="/integration">proportional creative integration</a>. Following the conditions of cooperation, you may end up developing amazing solutions able to coordinate the diversities of the individuals in a group, avoiding conflict. Contrast is part of the game, conflict is when contrast escalates into a form of violence. Equivalence, Trust, Care, Transparency, Freedom, Understanding and Diversity are your keys to foster solutions for evolving contrast in development and <a class="ae" href="/cooperation">cooperation</a>.</p>

  <p class="subheading equivalence center space margin">EQUIVALENCE: TURNS AND EXPERIMENTATION</p>
  <p class="base">Allow experimentation and use turns so that different proposed solutions have their space and <a class="ae" href="/cooperation#equivalence">equivalent</a> importance. Enjoy the way others would do things: you will learn how they think. Understanding others will let them follow you if they make a mistake or if their way is not so enjoyable.</p>

  <p class="subheading trust center space margin">TRUST: TIME AND EVALUATION</p>
  <p class="base">Give time its pace. Allow experience and adaptation to fix the situation and evaluate the results after a given amount of time. Sometimes fear may make people think in a negative way about events in the future. Faith in your solution and in those of others allows things to set up. <a class="at" href="/cooperation#trust">Trust</a> is important also in evaluations: when you see the solution tested has evidently damaged the group for a relevant amount of time, it will be easier to agree to a change.</p>

  <p class="subheading care center space margin">CARE: BETTER CONTEXTS, BETTER FEELINGS</p>
  <p class="base"><a class="ac" href="/cooperation#care">Care</a> means respect and good coordination. The context, the environment and the services should be observed. Are you in a beautiful place? Are plants or animals respected around you? Are there colors? Is there good food and water? Are you feeling good? Are you tired and need a pause? Are you afraid of something? Are you happy instead? Can you find an area of your body in which that happiness is?<br> These questions seem to be a lot but they are very important. They can create a funny and bright mood and give you time to relax a bit and be more comprehensive with each other.</p>

  <p class="subheading transparency center space margin">TRANSPARENCY: CONTEXTUAL POINT OF VIEW</p>
  <p class="base">The trick here is to expose everyone’s point of view in complete freedom. Be careful with this methodology and be ready to accept apparent unpleasant aspects. Bear very well in mind that what is requested is not to tell the truth right away, but to clearly expose <i>the contextual situation</i> from which your point of view <i>desumes</i> the truth you are going to expose. Saying "The wall is white" is different than saying "In my video camera, I see the blue wall as completely white."<br><br>
  In search for a <a class="ad" href="/integration">proportional creative integration</a>, tell in a <a class="ai" href="/cooperation#transparency">transparent</a> way what is the minimum you need to be comfortable in the current situation and what are the limitations you face in your position. Also, express your desires in first person, trying to be specific as much as you can. For example, a sentence like "You don't listen to me" becomes "I feel like as I am not able to be understood. I would really like if I could talk for 5 minutes, no more, without interruption."</p>

  <p class="subheading freedom center space margin">FREEDOM: THE RIGHT SPACE TO EVERYONE</p>
  <p class="base">Giving the right <a class="af" href="/cooperation#freedom">space</a> is a way to make people feel at ease without separating them. Nothing is worse than forcing to be together people who do not want to. If you are a few, try a pause or simply some space or distance between the people in conflict for a determined amount of time. If you are many, you can experience a live setup that foster cooperation organising an <a class="ac" href="/coopenspace">Open Space Cooperation</a>.</p>

  <p class="subheading understanding center space margin">UNDERSTANDING: COMMON CODES</p>
  <p class="base">Ask yourself what are the values you believe in when you have a contrast. The values or the motivations could be profoundly similar even in a wide difference of personal views. Choose together common and measurable criterias to evaluate the situation. Everyone of us is <a class="ad" href="/cooperation#diversity">different</a>, and everyone of us sees things with a different perspective, trying to be happy in this very complex world. The key in creating the feeling of cooperation is <a class="au" href="/cooperation#understanding">understanding</a> that everyone sees the world with complete different codes, so when you reciprocally share the way you see things it's possible to comprehend each other and find the right <a class="ad" href="/integration">integration</a>.</p>

  <p class="subheading diversity center space margin">DIVERSITY: INTEGRATION AND ROLES</p>
  <p class="base">Sometimes contrasts are based on two visions about a problem which do not exclude that much one another. Combining the two perspective in a <a class="ad" href="/integration">creative</a> way may result in a strong, effective and powerful solution.<br>If the contrast is instead based on individuals with <a class="ad" href="/cooperation#diversity">different</a> expertises, every one of them should have a role, based on their personal preferences and knowledge so that everyone has a responsibility in which they believe and its proper <a class="af" href="/cooperation#freedom">space</a> and responsibilities. Setting up some space between different skills is the way to integrate people's ideas. Everyone will feel part of the group without overlapping on each other. When the context is nice and there's the right
    <a class="ac" href="/cooperation#care">coordination</a> of roles, <a class="ae" href="/cooperation">cooperation</a> emerges and mutual enjoyment fulfills the group.</p>

  <p class="base"><a class="ae" href="/register">Join</a> and <a class="at" href="/participate">Participate</a> in Cooperacy to see how these solutions can be of help in <a class="ae" href="/spread">spreading</a> the good energy of cooperation.</p>
  </div>
</template>
  