<template>
  <div>
    <div class="page-container">
      <br /><img
        class="page-header"
        src="~/assets/image/page/banners/whitepaper.png"
      >
      <p class="base understanding">This white paper explains how the Cooperacy platform works in detail.</p>
      <p class="base">The platform is intended to develop the coomembers ideas. Cooperacy is the platform largest project, a real ecosystem. Any internal activity of Cooperacy is a project as well. Every project can be a part of other ones, or their home. All activities generated by the platform are co-owned by Cooperacy and its coomembers.</p>

      <p class="subheading understanding center space margin">THE COLLECTION FUND</p>
      <p class="base">Cooperacy <i>collection fund</i> is a collective amount of money generated by every member's one euro monthly subscription. One euro per month is 0.00000039 euros or 0.39 micro-euro per second:</p>
      <div style="overflow-x:auto;">
        <table style="width:100%;">
          <thead>
            <tr>
              <th class="baset understanding">Coomembers</th>
              <th class="baset understanding">&euro;/Second</th>
              <th class="baset understanding">Hour</th>
              <th class="baset understanding">Day</th>
              <th class="baset understanding">Month</th>
              <th class="baset understanding">Year</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td class="baset">1</td>
              <td class="baset">0.39 micro</td>
              <td class="baset">0.001</td>
              <td class="baset">0.033</td>
              <td class="baset">1</td>
              <td class="baset">12</td>
            </tr>
            <tr>
              <td class="baset">100</td>
              <td class="baset">0.000039</td>
              <td class="baset">0.139</td>
              <td class="baset">3.33</td>
              <td class="baset">100</td>
              <td class="baset">1200</td>
            </tr>
            <tr>
              <td class="baset">10k</td>
              <td class="baset">0.0039</td>
              <td class="baset">13.9</td>
              <td class="baset">333</td>
              <td class="baset">10k</td>
              <td class="baset">120k</td>
            </tr>
            <tr>
              <td class="baset">1M</td>
              <td class="baset">0.39</td>
              <td class="baset">1389</td>
              <td class="baset">33k</td>
              <td class="baset">1M</td>
              <td class="baset">12M</td>
            </tr>
            <tr>
              <td class="baset">1B</td>
              <td class="baset">386</td>
              <td class="baset">1389k</td>
              <td class="baset">33M</td>
              <td class="baset">1B</td>
              <td class="baset">12B</td>
            </tr>
            <tr>
              <td class="baset">7B (World)</td>
              <td class="baset">2700</td>
              <td class="baset">9.7M</td>
              <td class="baset">233M</td>
              <td class="baset">7B</td>
              <td class="baset">84B</td>
            </tr>
          </tbody>
        </table>
      </div>

      <p class="subheading understanding center space margin">PROJECTS</p>
      <p class="base">The money is allocated to the different ideas coming from the participants through their voting. Every second the microeuros are pre-allocated proportionally to the project ideas: the more the votes, the more the proportional amount of money. The collected funds are pre-allocated until the ideas budget is reached. When it happens, the idea turns into an "approval project" starting the budget release phase. After the approval phase is completed, the idea becomes an "active project", and its profits go back to the collection fund.</p>

      <p class="subheading understanding center space margin">BUDGET 0 IDEAS</p>
      <p class="base">Ideas may need no budget. For example, they can be a tool for a decision making supported by voting. Some of them, instead, like courses, concerts, dinners, parties.. may not require a budget but a minimum number of participants that commit themselves to the payment of a ticket or a fee, without which the ideas are not sustainable. All these ideas do not participate to the collection fund distribution, but their possible profit goes to the collection fund anyways, as all activities are co-owned by Cooperacy.</p>

      <p class="subheading understanding center space margin">AFTF MULTIDIMENSIONAL VOTING</p>
      <p class="base">In Cooperacy we don't vote for people, but for ideas. Both ideas and voting are anonymous until the ideas become projects. After that, all the information will be transparent for checking purposes. This is called AFTF, Anonymous First, Transparent Forever-after: the beginning anonymity allows to boost collective intelligence and transparency enhances cooperation afterwards. <br> Anybody can vote for as many ideas they want. In order to leverage more collective intelligence, there are different kinds of votes:
      </p><br>

      <p class="base equivalence">Equivalence</p>
      <p class="base">It determines the proportional allocation of funds. Technical: the proportions are calculated with the number of the equivalence votes the idea has, divided by the total of all the equivalence votes all the ideas have (Ei / Et ). Equivalence-voters become participants of the future projects.
      </p><br>

      <p class="base trust">Trust</p>
      <p class="base">Trust votes make the project skip the first budget step. Technical: if trust votes are more than 75% of equivalence votes (Ti > 75% Ei) the first budget step is directly approved. Trust votes in a "budget 0 idea" indicate participation as a Trustee, that is, as a client, affiliate, pre-buy, subscription to a course or pre-purchase to a concert. This vinculates the trustee to the payment of the relative pre-purchase or fee after the first milestone is passed.</p><br>

      <p class="base care">Care</p>
      <p class="base">It’s for sustainability projects or ones that generate emotional response in the voter. The emotional response in the future could also be generated thanks to biofeedback sensors. When care-voted, the project gains higher visibility. Technical: Ideas visibility is enhanced by Care votes percentages (Ci / Ct )</p><br>

      <p class="base transparency">Transparency</p>
      <p class="base">This vote determines wether the idea is hiding some information or cheating or spamming. Technical: if the number of transparency votes, subtracted of half of the trust votes, are more than 25% of Equivalence votes (Ii - 50% Ti > 25% Ei ) the idea or project is blocked until the values are back to normal ( Ii - 50% Ti &lt; 25% Ei ) After 90 days of blockage, the idea is removed and the budget is turned back to the collection fund. During this period the participants can better explain to voters the idea development in order to provoke a change in the number of transparency and trust votes. If the idea is unblocked, the count of 90 days is canceled. Transparency voters are never anonymous. Highly transparency-voted ideas go to a final year list in which the most transparency-voted idea wins the prize of joke/trolling idea of the year. (When clicking, insert an alert that explains the functioning). </p><br>

      <p class="base freedom">Freedom</p>
      <p class="base">Freedom-voting means you would like to work for the idea or participate into the decision making. Every project can instead be discussed and observed in full transparency anyways. Technical: if a hudget is requested, freedom-votes count for the requested hudget. Moreover, freedom-voters will be chosen automatically unless their number is higher than the requested hudget, in which case a selection will occur. If a hudget is not requested, the idea participants will first review the freedom-voters list for the budget "hudget" step. Freedom-voters automatically become participants when the project becomes active.</p><br>

      <p class="base understanding">Understanding</p>
      <p class="base">This vote refers to the idea comprehension/smartness/nerditude. It is an information for the idea proposer. Technical: if the understanding-votes are above the 75th percentile (Ui > Ût + Ût/2) the budget release step "Fine Tuning" is automatically approved. A number of understanding-votes will also be given by the Ecosystemic Learning artificial intelligence, that will evaluate data and contextual information.</p><br>

      <p class="base diversity">Diversity</p>
      <p class="base">When a project has a strong “bizardry” (diversity-votes), it has more opportunities to be randomly approved. Technical: ideas has a diversity percentage ( Di / Dt ). Every idea, the first day of a season (equinoxes and solstices), is given a random percentage value between 0% and 10%, to which the diversity percentage is added and then randomly multiplied by -1. The idea that has the highest “Bizardry” has a virtual added equivalence-votes percentage of +50% [( Ei + 50% Et ) / Et ].</p><br><br>

      <p class="base">Current minimum budget for funded ideas is 1000 euros, as according to crowdfunding sites statistics ideas with lower amounts averagely fail.<br>
        Any direct donation to an idea counts as dedicated donated budget. Donated budget and pre-allocated budget count for the idea budget to be turned into an approval project, but donated budget cannot be returned to the collection fund unless the idea is rescinded or abandoned.<br>
        Once the idea has reached the budget and/or hudget, the participants of the idea are kept frozen during the approval project phase until it is turned into an active project. The budget release milestones deadlines are chosen according to the Cooperacy <a
          class="af"
          href="/governance"
        >governance</a> scheme.<br>
        Eventual contrasts not resolved in the 7 budget milestones are solved with a transparent voting kept live for three days, in which the participants can change their votes. The coordinators have three more days to try to creatively integrate the contrasting positions according to the seven solutions. At the end of a week time, the milestone should be decided.<br>
        All the contrasting votes not integrated reduce the budget, which goes back to the collection fund. In that case, the project turns back to the idea state, keeping the milestones approved, and waits again for the fulfilment of the missing budget cut due to contrasting positions.<br>
        Highlighting colors can indicate different ideas types, like cyan for “educational”, violet for “scientific”, and green for “environmental” ones. You are free to use these labels, but if they are misleading they can make people downvote them. Some projects are geographic units, like cities or specific locations and are highlighted in blue.<br>
        When an idea becomes an approval project, the idea is “born”, and has a birthdate. When the approval becomes an active project it can receive a three level feedback by the coomembers (+,=,-).<br>
        In case of “death” of an active project, for example when a course ends, or a backery is sold, its final step is to be archived. This turns the active project into an archived one and the AI analyzes it while the participants may still give some feedback.<br>
        Participants Gender (M / F / Other) will be aggregated in order to inidicate in the future the project gender composition.<br>
        Projects may have internal project ideas, for example a language institute that wants to add a new language course. Budget ideas that want to be funded by the Cooperacy collection fund must be in the Cooperacy base project to receive any budget pre-allocation. Only afterwards they can be inserted as subprojects of any main project.<br>
      </p>

      <p class="subheading understanding center space margin">CO-DONATIONS</p>
      <p class="base">Co-donation is an alternative way in which you can help an idea to find its budget. When you hit on co-donate, you choose a maximum amount you are willing to donate for filling up the idea budget, if all the other co-donators are willing to donate the same. The system periodically evaluates the lowest of all amounts promised and multiplies for the number of the co-donators in order to see if the total budget is reached. If not, the system evaluates other combination possibilities able to reach the budget, like excluding lower donation amounts. Once a possible co-donation is found, the idea is turned into a project and the codonations are billed to your bank account, credit card or any other possibility the website allows.</p>

      <p class="subheading understanding center space margin">BUDGET RELEASE STEPS</p>
      <p class="base">The budget release process is divided into 7 steps which have a three days approval voting time in which the process could be halted and the people in charge can be changed for corruption or security reasons. Only people who equivalence-voted, participated or are relative to the module will be notified of the phases. Participants are therefore allowed to vote even if they are external to the module but only if they really care, as they won’t be notified otherwise. Every step is also voted for its transparency and sustainability.</p><br>
      <div style="overflow-x:auto;">
        <table style="width:100%;">
          <thead>
            <tr>
              <th class="baset understanding">STEPS</th>
              <th class="baset understanding">% Released</th>
              <th class="baset understanding">% Incremental</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td class="baset">Business Plan</td>
              <td class="baset">3%</td>
              <td class="baset">3%</td>
            </tr>
            <tr>
              <td class="baset">Human Resources</td>
              <td class="baset">10%</td>
              <td class="baset">13%</td>
            </tr>
            <tr>
              <td class="baset">Setup</td>
              <td class="baset">12%</td>
              <td class="baset">25%</td>
            </tr>
            <tr>
              <td class="baset">Production</td>
              <td class="baset">50%</td>
              <td class="baset">75%</td>
            </tr>
            <tr>
              <td class="baset">Kick Off</td>
              <td class="baset">12%</td>
              <td class="baset">87%</td>
            </tr>
            <tr>
              <td class="baset">Fine Tuning</td>
              <td class="baset">10%</td>
              <td class="baset">97%</td>
            </tr>
            <tr>
              <td class="baset">Celebrate</td>
              <td class="baset">3%</td>
              <td class="baset">100%</td>
            </tr>
          </tbody>
        </table>
      </div>

      <p class="subheading understanding center space margin">THE COOPERACY PROJECTS AS MODULES</p>
      <p class="base">As you see, there is a modular design in the projects. The modularity allows for an organic and circle-like approach that is able to create open source blueprints for the whole platform community. Any project can have a "home" and internal "parts".<br>
        Every module has:<br><br>
        1. Information set</p>
      <p class="base">
        • Title (and proposers when anonymity ends) <br>
        • Representative image <br>
        • Subheading or objective of the project<br>
        • Home and parts<br>
        • Tags<br>
        • Location<br>
        • Voting allowance (for specific local projects)<br></p>
      <p class="base">
        2. Coordinators: the ears of the module, they listen to what the participants want to do and execute it.<br>
        3. Participants: active hands of the module. Minimum 2, the coordinators, advised maximum 150.<br>
        4. Experts: possible special participants who do not vote but give advices. The “mouth” of the module.<br>
        5. Reporters: two “eyes” of the module, they write reports and compare the module with the business plan.<br>
        6. Hudget: the number of committed people required to realize the module.<br>
        7. Feed: the module is continuously subject of feedback by the participants and the voters. Even after years any participant can decide if something was good or bad, influencing the memory of the system. A simple feedback history is available: after 1 month (M), 1 season (S), 1 year (Y) and after 7 years (7).<br>
        Feedback can be only of three kinds: HAPPY(+) MEDIUM(=) SAD(-)<br><br>
        The projects represent the voting unit of Cooperacy. They have this main lifecycle:<br> </p>
      <p class="base">
        • Project Idea: the project is proposed – it is usually anonymous and it could be also voted anonymously<br>
        • Approval Project: the idea reaches its budget or hudget, becomes a project, anonymity ends, budget phase starts;<br>
        • Active Project: the project becomes an active one, its profits go back to the collection fund;<br>
        • Archived Project: when the mission is accomplished or terminated the project “dies”. This is not a bitter end, it means the project goes in the archive in order to influence future modules and for future reference;<br></p>
    </div>
  </div>
</template>
